version: '3'
services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - max
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    expose:
      - 5432
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: finalboss
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - ivan
  front-end:
    build:
      context: ../webfinallab/
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - max
networks:
  max:


